<?php

use Illuminate\Database\Seeder;

class ConfigStatusesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        \DB::table('config_statuses')->delete();

        \DB::table('config_statuses')->insert(array(
            0 => array(
                'id' => 1,
                'slug' => 'issue-today',
                'type' => 'issue',
                'title' => 'Today',
                'description' => 'changed status to "today"',
                'position' => 1,
                'color' => 'daa724',
                'is_closed' => null,
                'default' => 1,
            ),
            1 => array(
                'id' => 2,
                'slug' => 'issue-done',
                'type' => 'issue',
                'description' => 'changed status to "done"',
                'title' => 'Done',
                'position' => 2,
                'color' => '079a0d',
                'is_closed' => 1,
                'default' => null,
            ),
            2 => array(
                'id' => 3,
                'slug' => 'issue-monday',
                'type' => 'issue',
                'title' => 'Monday',
                'description' => 'changed status to "monday"',
                'position' => 3,
                'color' => '3745be',
                'is_closed' => null,
                'default' => 1,
            ),
            3 => array(
                'id' => 4,
                'slug' => 'issue-tuesday',
                'type' => 'issue',
                'title' => 'Tuesday',
                'description' => 'changed status to "tuesday"',
                'position' => 4,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
            4 => array(
                'id' => 5,
                'slug' => 'note-added',
                'type' => 'note',
                'title' => 'added',
                'description' => 'added a note',
                'position' => 0,
                'color' => 'f0f0f0',
                'is_closed' => null,
                'default' => 1,
            ),
            5 => array(
                'id' => 6,
                'slug' => 'sprint-open',
                'type' => 'sprint',
                'title' => 'Open',
                'description' => 'open a sprint',
                'position' => 1,
                'color' => '079a0d',
                'is_closed' => null,
                'default' => null,
            ),
            6 => array(
                'id' => 7,
                'slug' => 'sprint-closed',
                'type' => 'sprint',
                'title' => 'Closed',
                'description' => 'closed a sprint',
                'position' => 3,
                'color' => '3745be',
                'is_closed' => 1,
                'default' => null,
            ),
            7 => array(
                'id' => 8,
                'slug' => 'sprint-standby',
                'type' => 'sprint',
                'title' => 'Standby',
                'description' => 'standby a sprint',
                'position' => 2,
                'color' => '8c023f',
                'is_closed' => 1,
                'default' => 1,
            ),
            8 => array(
                'id' => 9,
                'slug' => 'attachment-added',
                'type' => 'attachment',
                'title' => 'Added',
                'description' => 'added an attachment',
                'position' => 1,
                'color' => '6272a4',
                'is_closed' => null,
                'default' => 1,
            ),
            9 => array(
                'id' => 10,
                'slug' => 'comment-added',
                'type' => 'comment',
                'title' => 'Commented',
                'description' => 'added a comment',
                'position' => 1,
                'color' => '3745be',
                'is_closed' => null,
                'default' => 1,
            ),
            10 => array(
                'id' => 11,
                'slug' => 'label-assigned',
                'type' => 'label',
                'title' => 'Assigned',
                'description' => 'assigned a label',
                'position' => 1,
                'color' => '3745be',
                'is_closed' => null,
                'default' => 1,
            ),
            11 => array(
                'id' => 12,
                'slug' => 'issue-wednesday',
                'type' => 'issue',
                'title' => 'Wednesday',
                'description' => 'changed status to "wednesday"',
                'position' => 5,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
            12 => array(
                'id' => 13,
                'slug' => 'issue-thursday',
                'type' => 'issue',
                'title' => 'Thursday',
                'description' => 'changed status to "thursday"',
                'position' => 6,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
            13 => array(
                'id' => 14,
                'slug' => 'issue-friday',
                'type' => 'issue',
                'title' => 'Friday',
                'description' => 'changed status to "friday"',
                'position' => 7,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
            14 => array(
                'id' => 15,
                'slug' => 'issue-saturday',
                'type' => 'issue',
                'title' => 'Saturday',
                'description' => 'changed status to "saturday"',
                'position' => 8,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
            15 => array(
                'id' => 16,
                'slug' => 'issue-sunday',
                'type' => 'issue',
                'title' => 'Sunday',
                'description' => 'changed status to "sunday"',
                'position' => 9,
                'color' => '8c023f',
                'is_closed' => null,
                'default' => 1,
            ),
        ));
    }
}
